<?xml version="1.0"?>

<package format="3">

  <name>wheeltec_autorace_description</name>

  <version>0.0.1</version>

  <description>
    Robot models and simulation assets for the JKK 2D Gazebo Wheeltec project.
  </description>

  <maintainer email="kovacspatrik200436@gmail.com">
    Kovacs Patrik Janos
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros_gz_sim</exec_depend>

  <export>

    <build_type>ament_cmake</build_type>

    <gazebo_ros
      gazebo_model_path="${prefix}/../"/>

  </export>

</package>
